#1. k: v # k v 之間 是空格區分
#2. 屬性有層級關係，使用下一行，空兩個空格
#3. 左側對齊的屬性，表示同一層級
server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: 172.17.0.2
      port: 6379
#  datasource:
#    url: aaaa